# Generated by Django 4.0.5 on 2022-06-18 15:01

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtaa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='hood_photo')),
                ('hood_name', models.CharField(max_length=100, null=True)),
                ('occupants_count', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtaa.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hood_name'],
            },
        ),
    ]
